/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../schema.json
export type InfoSection = {
	_type: 'infoSection'
	heading?: string
	subheading?: string
	content?: BlockContent
}

export type PostReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'post'
}

export type Link = {
	_type: 'link'
	linkType?: 'href' | 'post'
	href?: string
	post?: PostReference
	openInNewTab?: boolean
}

export type BlockContent = Array<{
	children?: Array<{
		marks?: Array<string>
		text?: string
		_type: 'span'
		_key: string
	}>
	style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
	listItem?: 'bullet' | 'number'
	markDefs?: Array<{
		linkType?: 'href' | 'post'
		href?: string
		post?: PostReference
		openInNewTab?: boolean
		_type: 'link'
		_key: string
	}>
	level?: number
	_type: 'block'
	_key: string
}>

export type SanityImageAssetReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Transformation = {
	_id: string
	_type: 'transformation'
	_createdAt: string
	_updatedAt: string
	_rev: string
	name: string
	age: number
	durationMonths?: number
	imageBefore: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	imageAfter: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	stats?: Array<{
		label: string
		before: string
		after: string
		_key: string
	}>
	description?: BlockContent
}

export type SanityImageCrop = {
	_type: 'sanity.imageCrop'
	top: number
	bottom: number
	left: number
	right: number
}

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot'
	x: number
	y: number
	height: number
	width: number
}

export type Testimonial = {
	_id: string
	_type: 'testimonial'
	_createdAt: string
	_updatedAt: string
	_rev: string
	orderRank?: string
	name: string
	quote: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal'
		listItem?: never
		markDefs?: null
		level?: number
		_type: 'block'
		_key: string
	}>
	image?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	rating: 1 | 2 | 3 | 4 | 5
}

export type Service = {
	_id: string
	_type: 'service'
	_createdAt: string
	_updatedAt: string
	_rev: string
	orderRank?: string
	name: string
	label: string
	image: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	icon: LucideIcon
	ctaLabel: string
	order?: number
}

export type LucideIcon = string

export type LegalPage = {
	_id: string
	_type: 'legalPage'
	_createdAt: string
	_updatedAt: string
	_rev: string
	noIndex?: boolean
	title: string
	slug: Slug
	intro?: string
	sections?: Array<
		{
			_key: string
		} & InfoSection
	>
	lastUpdated?: string
	seoTitle?: string
	seoDescription?: string
}

export type Slug = {
	_type: 'slug'
	current: string
	source?: string
}

export type Post = {
	_id: string
	_type: 'post'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title: string
	slug: Slug
	content?: BlockContent
	excerpt?: string
	coverImage: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	date?: string
}

export type SanityFileAssetReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type Gallery = {
	_id: string
	_type: 'gallery'
	_createdAt: string
	_updatedAt: string
	_rev: string
	items?: Array<
		| {
				image: {
					asset?: SanityImageAssetReference
					media?: unknown
					hotspot?: SanityImageHotspot
					crop?: SanityImageCrop
					alt?: string
					_type: 'image'
				}
				caption?: string
				_type: 'galleryImage'
				_key: string
		  }
		| {
				video: {
					asset?: SanityFileAssetReference
					media?: unknown
					_type: 'file'
				}
				thumbnail: {
					asset?: SanityImageAssetReference
					media?: unknown
					hotspot?: SanityImageHotspot
					crop?: SanityImageCrop
					alt?: string
					_type: 'image'
				}
				caption?: string
				_type: 'galleryVideo'
				_key: string
		  }
	>
}

export type About = {
	_id: string
	_type: 'about'
	_createdAt: string
	_updatedAt: string
	_rev: string
	photos: Array<{
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
		_key: string
	}>
	certificates?: Array<{
		image: {
			asset?: SanityImageAssetReference
			media?: unknown
			hotspot?: SanityImageHotspot
			crop?: SanityImageCrop
			_type: 'image'
		}
		label: string
		_key: string
	}>
}

export type SanityAssistInstructionTask = {
	_type: 'sanity.assist.instructionTask'
	path?: string
	instructionKey?: string
	started?: string
	updated?: string
	info?: string
}

export type SanityAssistTaskStatus = {
	_type: 'sanity.assist.task.status'
	tasks?: Array<
		{
			_key: string
		} & SanityAssistInstructionTask
	>
}

export type SanityAssistSchemaTypeAnnotations = {
	_type: 'sanity.assist.schemaType.annotations'
	title?: string
	fields?: Array<
		{
			_key: string
		} & SanityAssistSchemaTypeField
	>
}

export type SanityAssistOutputType = {
	_type: 'sanity.assist.output.type'
	type?: string
}

export type SanityAssistOutputField = {
	_type: 'sanity.assist.output.field'
	path?: string
}

export type AssistInstructionContextReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
	_type: 'sanity.assist.instruction.context'
	reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
	_id: string
	_type: 'assist.instruction.context'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	context?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal'
		listItem?: never
		markDefs?: null
		level?: number
		_type: 'block'
		_key: string
	}>
}

export type SanityAssistInstructionUserInput = {
	_type: 'sanity.assist.instruction.userInput'
	message: string
	description?: string
}

export type SanityAssistInstructionPrompt = Array<{
	children?: Array<
		| {
				marks?: Array<string>
				text?: string
				_type: 'span'
				_key: string
		  }
		| ({
				_key: string
		  } & SanityAssistInstructionFieldRef)
		| ({
				_key: string
		  } & SanityAssistInstructionContext)
		| ({
				_key: string
		  } & SanityAssistInstructionUserInput)
	>
	style?: 'normal'
	listItem?: never
	markDefs?: null
	level?: number
	_type: 'block'
	_key: string
}>

export type SanityAssistInstructionFieldRef = {
	_type: 'sanity.assist.instruction.fieldRef'
	path?: string
}

export type SanityAssistInstruction = {
	_type: 'sanity.assist.instruction'
	prompt?: SanityAssistInstructionPrompt
	icon?: string
	title?: string
	userId?: string
	createdById?: string
	output?: Array<
		| ({
				_key: string
		  } & SanityAssistOutputField)
		| ({
				_key: string
		  } & SanityAssistOutputType)
	>
}

export type SanityAssistSchemaTypeField = {
	_type: 'sanity.assist.schemaType.field'
	path?: string
	instructions?: Array<
		{
			_key: string
		} & SanityAssistInstruction
	>
}

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch'
	background?: string
	foreground?: string
	population?: number
	title?: string
}

export type SanityImagePalette = {
	_type: 'sanity.imagePalette'
	darkMuted?: SanityImagePaletteSwatch
	lightVibrant?: SanityImagePaletteSwatch
	darkVibrant?: SanityImagePaletteSwatch
	vibrant?: SanityImagePaletteSwatch
	dominant?: SanityImagePaletteSwatch
	lightMuted?: SanityImagePaletteSwatch
	muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions'
	height: number
	width: number
	aspectRatio: number
}

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata'
	location?: Geopoint
	dimensions?: SanityImageDimensions
	palette?: SanityImagePalette
	lqip?: string
	blurHash?: string
	thumbHash?: string
	hasAlpha?: boolean
	isOpaque?: boolean
}

export type SanityFileAsset = {
	_id: string
	_type: 'sanity.fileAsset'
	_createdAt: string
	_updatedAt: string
	_rev: string
	originalFilename?: string
	label?: string
	title?: string
	description?: string
	altText?: string
	sha1hash: string
	extension: string
	mimeType: string
	size: number
	assetId: string
	uploadId?: string
	path: string
	url: string
	source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData'
	name?: string
	id?: string
	url?: string
}

export type SanityImageAsset = {
	_id: string
	_type: 'sanity.imageAsset'
	_createdAt: string
	_updatedAt: string
	_rev: string
	originalFilename?: string
	label?: string
	title?: string
	description?: string
	altText?: string
	sha1hash: string
	extension: string
	mimeType: string
	size: number
	assetId: string
	uploadId?: string
	path: string
	url: string
	metadata?: SanityImageMetadata
	source?: SanityAssetSourceData
}

export type Geopoint = {
	_type: 'geopoint'
	lat?: number
	lng?: number
	alt?: number
}

export type AllSanitySchemaTypes =
	| InfoSection
	| PostReference
	| Link
	| BlockContent
	| SanityImageAssetReference
	| Transformation
	| SanityImageCrop
	| SanityImageHotspot
	| Testimonial
	| Service
	| LucideIcon
	| LegalPage
	| Slug
	| Post
	| SanityFileAssetReference
	| Gallery
	| About
	| SanityAssistInstructionTask
	| SanityAssistTaskStatus
	| SanityAssistSchemaTypeAnnotations
	| SanityAssistOutputType
	| SanityAssistOutputField
	| AssistInstructionContextReference
	| SanityAssistInstructionContext
	| AssistInstructionContext
	| SanityAssistInstructionUserInput
	| SanityAssistInstructionPrompt
	| SanityAssistInstructionFieldRef
	| SanityAssistInstruction
	| SanityAssistSchemaTypeField
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageMetadata
	| SanityFileAsset
	| SanityAssetSourceData
	| SanityImageAsset
	| Geopoint

// Source: src/sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]
export type SettingsQueryResult = null

// Source: src/sanity/lib/queries.ts
// Variable: sitemapData
// Query: *[_type == "post" || _type == "legalPage" && defined(slug.current)] | order(_type asc) {    "slug": slug.current,    _type,    _updatedAt,  }
export type SitemapDataResult = Array<
	| {
			slug: string
			_type: 'legalPage'
			_updatedAt: string
	  }
	| {
			slug: string
			_type: 'post'
			_updatedAt: string
	  }
>

// Source: src/sanity/lib/queries.ts
// Variable: allPostsQuery
// Query: *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  }
export type AllPostsQueryResult = Array<{
	_id: string
	status: 'draft' | 'published'
	title: string
	slug: string
	excerpt: string | null
	coverImage: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	date: string
}>

// Source: src/sanity/lib/queries.ts
// Variable: morePostsQuery
// Query: *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  }
export type MorePostsQueryResult = Array<{
	_id: string
	status: 'draft' | 'published'
	title: string
	slug: string
	excerpt: string | null
	coverImage: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	date: string
}>

// Source: src/sanity/lib/queries.ts
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug] [0] {    content[]{    ...,    markDefs[]{      ...,        _type == "link" => {    "post": post->slug.current,    "legalPage": legalPage->slug.current  }    }  },      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  }
export type PostQueryResult = {
	content: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
		listItem?: 'bullet' | 'number'
		markDefs: Array<{
			linkType?: 'href' | 'post'
			href?: string
			post: string | null
			openInNewTab?: boolean
			_type: 'link'
			_key: string
			legalPage: null
		}> | null
		level?: number
		_type: 'block'
		_key: string
	}> | null
	_id: string
	status: 'draft' | 'published'
	title: string
	slug: string
	excerpt: string | null
	coverImage: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	date: string
} | null

// Source: src/sanity/lib/queries.ts
// Variable: postPagesSlugs
// Query: *[_type == "post" && defined(slug.current)]  {"slug": slug.current}
export type PostPagesSlugsResult = Array<{
	slug: string
}>

// Source: src/sanity/lib/queries.ts
// Variable: faqQuery
// Query: *[_type == "faq"] | order(orderRank) {    question,    answer  }
export type FaqQueryResult = Array<never>

// Source: src/sanity/lib/queries.ts
// Variable: servicesQuery
// Query: *[_type == "service"] | order(order asc) {    _id,    name,    label,    image,    icon,    ctaLabel,  }
export type ServicesQueryResult = Array<{
	_id: string
	name: string
	label: string
	image: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	icon: LucideIcon
	ctaLabel: string
}>

// Source: src/sanity/lib/queries.ts
// Variable: transformationsQuery
// Query: *[_type == "transformation"] | order(_createdAt asc) {    _id,    name,    age,    durationMonths,    imageBefore,    imageAfter,    stats[] { _key, label, before, after },    description[]{      ...,      markDefs[]{        ...,        _type == "link" => {          "post": post->slug.current,          "legalPage": legalPage->slug.current        }      }    }  }
export type TransformationsQueryResult = Array<{
	_id: string
	name: string
	age: number
	durationMonths: number | null
	imageBefore: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	imageAfter: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	stats: Array<{
		_key: string
		label: string
		before: string
		after: string
	}> | null
	description: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
		listItem?: 'bullet' | 'number'
		markDefs: Array<{
			linkType?: 'href' | 'post'
			href?: string
			post: string | null
			openInNewTab?: boolean
			_type: 'link'
			_key: string
			legalPage: null
		}> | null
		level?: number
		_type: 'block'
		_key: string
	}> | null
}>

// Source: src/sanity/lib/queries.ts
// Variable: aboutQuery
// Query: *[_type == "about"][0] {    photos,    certificates[] {      _key,      image,      label    }  }
export type AboutQueryResult = {
	photos: Array<{
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
		_key: string
	}>
	certificates: Array<{
		_key: string
		image: {
			asset?: SanityImageAssetReference
			media?: unknown
			hotspot?: SanityImageHotspot
			crop?: SanityImageCrop
			_type: 'image'
		}
		label: string
	}> | null
} | null

// Source: src/sanity/lib/queries.ts
// Variable: testimonialsQuery
// Query: *[_type == "testimonial"] | order(orderRank asc, _createdAt asc) {    _id,    name,    quote,    image,    rating  }
export type TestimonialsQueryResult = Array<{
	_id: string
	name: string
	quote: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal'
		listItem?: never
		markDefs?: null
		level?: number
		_type: 'block'
		_key: string
	}>
	image: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	} | null
	rating: 1 | 2 | 3 | 4 | 5
}>

// Source: src/sanity/lib/queries.ts
// Variable: galleryQuery
// Query: *[_type == "gallery"][0] {    items[] {      _key,      _type,      caption,      image,      thumbnail,      "videoUrl": video.asset->url    }  }
export type GalleryQueryResult = {
	items: Array<
		| {
				_key: string
				_type: 'galleryImage'
				caption: string | null
				image: {
					asset?: SanityImageAssetReference
					media?: unknown
					hotspot?: SanityImageHotspot
					crop?: SanityImageCrop
					alt?: string
					_type: 'image'
				}
				thumbnail: null
				videoUrl: null
		  }
		| {
				_key: string
				_type: 'galleryVideo'
				caption: string | null
				image: null
				thumbnail: {
					asset?: SanityImageAssetReference
					media?: unknown
					hotspot?: SanityImageHotspot
					crop?: SanityImageCrop
					alt?: string
					_type: 'image'
				}
				videoUrl: string | null
		  }
	> | null
} | null

// Source: src/sanity/lib/queries.ts
// Variable: legalPageQuery
// Query: *[_type == "legalPage" && slug.current == $slug][0]{    _id, title, intro, lastUpdated,    "slug": slug.current,    sections[]{      _key, title, collapsedByDefault, anchor,      content    },    seoTitle, seoDescription,    noIndex,  }
export type LegalPageQueryResult = {
	_id: string
	title: string
	intro: string | null
	lastUpdated: string | null
	slug: string
	sections: Array<{
		_key: string
		title: null
		collapsedByDefault: null
		anchor: null
		content: BlockContent | null
	}> | null
	seoTitle: string | null
	seoDescription: string | null
	noIndex: boolean | null
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
	interface SanityQueries {
		'*[_type == "settings"][0]': SettingsQueryResult
		'\n  *[_type == "post" || _type == "legalPage" && defined(slug.current)] | order(_type asc) {\n    "slug": slug.current,\n    _type,\n    _updatedAt,\n  }\n': SitemapDataResult
		'\n  *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n\n  }\n': AllPostsQueryResult
		'\n  *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n\n  }\n': MorePostsQueryResult
		'\n  *[_type == "post" && slug.current == $slug] [0] {\n    content[]{\n    ...,\n    markDefs[]{\n      ...,\n      \n  _type == "link" => {\n    "post": post->slug.current,\n    "legalPage": legalPage->slug.current\n  }\n\n    }\n  },\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n\n  }\n': PostQueryResult
		'\n  *[_type == "post" && defined(slug.current)]\n  {"slug": slug.current}\n': PostPagesSlugsResult
		'\n  *[_type == "faq"] | order(orderRank) {\n    question,\n    answer\n  }\n': FaqQueryResult
		'\n  *[_type == "service"] | order(order asc) {\n    _id,\n    name,\n    label,\n    image,\n    icon,\n    ctaLabel,\n  }\n': ServicesQueryResult
		'\n  *[_type == "transformation"] | order(_createdAt asc) {\n    _id,\n    name,\n    age,\n    durationMonths,\n    imageBefore,\n    imageAfter,\n    stats[] { _key, label, before, after },\n    description[]{\n      ...,\n      markDefs[]{\n        ...,\n        _type == "link" => {\n          "post": post->slug.current,\n          "legalPage": legalPage->slug.current\n        }\n      }\n    }\n  }\n': TransformationsQueryResult
		'\n  *[_type == "about"][0] {\n    photos,\n    certificates[] {\n      _key,\n      image,\n      label\n    }\n  }\n': AboutQueryResult
		'\n  *[_type == "testimonial"] | order(orderRank asc, _createdAt asc) {\n    _id,\n    name,\n    quote,\n    image,\n    rating\n  }\n': TestimonialsQueryResult
		'\n  *[_type == "gallery"][0] {\n    items[] {\n      _key,\n      _type,\n      caption,\n      image,\n      thumbnail,\n      "videoUrl": video.asset->url\n    }\n  }\n': GalleryQueryResult
		'\n  *[_type == "legalPage" && slug.current == $slug][0]{\n    _id, title, intro, lastUpdated,\n    "slug": slug.current,\n    sections[]{\n      _key, title, collapsedByDefault, anchor,\n      content\n    },\n    seoTitle, seoDescription,\n    noIndex,\n  }\n': LegalPageQueryResult
	}
}
